apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
spec:
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  accessModes:
    {{- toYaml .Values.pvc.accessModes  |  nindent 4 }}
  storageClassName: {{ .Values.pvc.storageClassName }}
