apiVersion: v1
kind: PersistentVolume
metadata:
  name: jx-payments-volume
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  hostPath:
    path: /var/jx-payments-persistent-file
    type: FileOrCreate
