apiVersion: v1
kind: Service
metadata:
  name: jx-payments-service
spec:
  selector:
    app: jx-payments
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
      nodePort: 30000